### ISSUE TITLE
Ethan: upload

### ISSUE THREAD

**Issue by aaroncarsonart** [aaroncarsonart/OpenDoor#2]
Please fix this issue in Github using the website.

**Comment by netwarior** [comment]
what issue?

**Comment by aaroncarsonart** [comment]
Good, I see that you posted.  Do you not have a button that says "close" or "close and comment"?
]

**Comment by EthanEiter** [comment]
ya

**Comment by EthanEiter** [comment]
Accidentally pushed close and comment the first time

**Comment by aaroncarsonart** [comment]
Hey, if you can close it, that's good.  I was thinking maybe only I could close it.

**Comment by aaroncarsonart** [comment]
Can you close it now?

**Comment by aaroncarsonart** [comment]
sweet, that works then.

**Comment by EthanEiter** [comment]
yup
